# Site
name: "Village Blog"
title: "Village Blog"
description: "Welcome to the Village Childcare Blog!"
logo: 'assets/images/Village2-01.png'
baseurl: 
google_analytics: 'UA-22916797-9'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: 'taylor@joinourvillage.com'
# Authors
authors:
  Taylor:
    name: Taylor Clark
    display_name: Taylor
    avatar: 'assets/images/taylor_avatar.png'
    email: taylor@joinourvillage.com
    description: "Taylor live in Austin Texas with his wife and two dogs."
  Drew:
    name: Drew Giovannoli
    display_name: Drew    
    avatar: 'assets/images/small headshot.jpeg'
    email: hello@villagechildcare.co
    description: "" 
  Rachel:
    name: Rachel Edmonson
    display_name: Rachel Edmonson  
    avatar: 'assets/images/village_logo_big.png'
    email: hello@villagechildcare.co
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
